### ISSUE TITLE
table go brrrrrrrrr

### ISSUE THREAD

**Issue by RandomExplosion** [Nigecat/Plexi#132]
**Is your feature request related to a problem? Please describe.**
The table stays flipped

**Describe the solution you'd like**
Plexi should unflip tables and make an annoyed face

**Describe alternatives you've considered**
yOu wOuLdNt LeAvE A TaBLe FlIPPEd iN YoUR oWN HoUSE

**Additional context**
Context sold separately

**Scope of the feature**

**Comment by Little-Sis** [comment]
yes
